name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build and deploy with Docker Compose
        run: |
          docker-compose up -d --build \
            --env VITE_SERVER_BASE_URL=${{ env.VITE_SERVER_BASE_URL }} \
            --env MONGODB_ATLAS_CONNECTION_STRING=${{ env.MONGODB_ATLAS_CONNECTION_STRING }} \
            --env JWT_SECRET=${{ secrets.JWT_SECRET }} \
            --env FRONTEND_URL=${{ env.FRONTEND_URL }}

      # - name: Build the Docker image
      #  run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
